# =============================================================================
# Конфигурация Conda окружения для проекта Game Script Generator
# Автор: OrionFLASH
# Описание: Определяет структуру Conda окружения с необходимыми зависимостями
# =============================================================================

# Название окружения
name: game_script_env

# Версия Python
channels:
  - conda-forge
  - defaults

# Основные зависимости Conda
dependencies:
  - python=3.9        # Версия Python
  - pip               # Менеджер пакетов Python
  
  # Основные библиотеки для работы с данными
  - pandas=1.5.3      # Библиотека для анализа и обработки данных
  - numpy=1.24.3      # Библиотека для численных вычислений
  - openpyxl=3.1.2    # Библиотека для работы с Excel файлами
  
  # Дополнительные зависимости через pip (удалены - не используются)
  # - pip:
  #   - pyperclip==1.8.2  # Копирование текста в системный буфер обмена 